# Generated by Django 2.2.4 on 2020-09-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=-1, verbose_name='order')),
                ('name', models.CharField(max_length=200, verbose_name='skill name')),
                ('damage', models.CharField(max_length=200, verbose_name='Damage')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hero.Hero')),
            ],
        ),
    ]
