# Generated by Django 2.2.4 on 2020-09-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='skill name')),
                ('trigger', models.CharField(max_length=10, verbose_name='Trigger')),
                ('damage', models.CharField(max_length=200, verbose_name='Damage')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='hero.Skill')),
            ],
        ),
    ]
